### ISSUE TITLE
Enhancement: Add a Pensoft button

### ISSUE THREAD

**Issue by timrobertson100** [gbif/ipt#1171] opened 2015-06-08 10:53 UTC
Pensoft are trying to make it as simple as possible to allow users to publish data papers.  The IPT currently allows users to download the metadata in RTF and upload it into a journal.

Pensoft would like to take this further by enabling a publisher to click a button in the IPT, which would open a new tab in the browser on a Pensoft site, where a person could log in, and after logging in, would be presented with a pre-filled set of forms based on the EML content (i.e. as you open the Pensoft tab, you provide the callback URL for the Pensoft system to get the EML).  

I propose this be added and that an administration setting is added to control if the "Open in Pensoft BDJ" link is shown on the dataset management page or not.  Future journals might follow later.

**Comment by peterdesmet** [comment] 2015-06-08 11:32
Why not do it the other way around? If you are on the Pensoft website, you can easily start your paper by providing the URL of a resource on IPT. That way, it is scalable to other journals without adding options to the IPT.

Does Pensoft require any new format in which the metadata is expressed by the IPT for this functionality?

**Comment by timrobertson100** [comment] 2015-06-08 11:38
No - and that way is already possible I understand.  This was just to help provide a quick link for IPT users.

**Comment by dagendresen** [comment] 2015-06-08 11:43
The data owners most relevant for writing the data paper are very seldom (?) the same as the technical admins of the IPT. A button from inside the IPT is thus of limited value (?). A button from the respective dataset page in the GBIF portal might perhaps be more useful - at least the respective data owner might be more likely to find the button than expecting them to look inside the IPT...? Perhaps the data owner (contact persons) could sign up to get a user account at the portal and for this user account to be linked to the respective datasets with role "data owner contact person".

**Comment by peterdesmet** [comment] 2015-06-08 11:44
What is the main goal of this button? To encourage people to publish data papers via Pensoft, to help them discover this possibility? I'm not the right user to answer this, but how do IPT users typically learn about this? How do they decide they are going to write a data paper? I don't know if a button is going to help...

**Comment by timrobertson100** [comment] 2015-06-08 12:08
I don't see any of the comments above as mutually exclusive.  It's all geared around raising visibility and simplifying the process.

@peterdesmet - if someone is taking the effort to fill in metadata using the IPT, does it do any harm to have information about data papers so they can answer those questions and then have an easy option to hop to the BDJ to continue?

@dagendresen - It is the case that some (not all) people charged with filling the metadata on a dataset in the IPT will be the same as authoring a data paper.  There is no reason why it should not be linked from other places too though.

**Comment by dschigel** [comment] 2015-10-02 11:56
Hi, Lyubomir plans a PR campaign about this button, and yes, we need clarity on that. We have discussed this last week with Lyubo, agreeing that it's dataset publishers (& originators) who would benefit from this smooth ms generation most. For the random data browsing / downloading guys it would be far too easy to start writing ms like "Lizards of North America", so it is fairly natural so the button is on IPT. Publishers & originators are a good target audience, they often fall into acknowledgements only, if at all, in the publication circle of those with analytical and hypotheses driven approach. This is the way for them to step out from the shadow. In effect, it should improve the visibility of dataset in a more academic package, so double effect for the same matadata filling effort. I think, if people know that there is a solid publication chance in the end, the metadata filling culture will improve, it's a good carrot.

**Comment by dshorthouse** [comment] 2015-10-02 12:14
I'm in agreement with everyone who has expressed uncertainty about the utility of this button. I don't expect a PR blitz will result in more data papers, except that it might re-articulate that an IPT can be used to publish a data paper to Pensoft. It's a difficult enough task getting potential data owners to create and maintain an account in an IPT, let alone have them fill out the metadata. Such a button, buried within an IPT, is unlikely to lead to discovery of the capability. Account holders as @dagendresen points out are typically the technical staff far removed from the potential data paper author. I also caution that such a button begins to partition audiences and end-users of an IPT - a small audience to begin with; not all users have the means or the interest in a data paper. As a result, the user experience gets a bit more muddled in an already busy tool.

**Comment by kbraak** [comment] 2016-10-11 12:35
I wanted to update everyone about the [Arpha writing tool](http://arpha.pensoft.net/) from Pensoft, a publishing platform that allows you to import a data paper manuscript from a GBIF EML file. In short the way it works is you log into Arpha, select the desired journal and article type, then you can upload an EML file that initiates the manuscript. More information about how the import works can be found [here](http://arpha.pensoft.net/tips/?tip=24). 

In my opinion it would be more valuable for GBIF to spend its time promoting this service for example on http://www.gbif.org/publishing-data/data-papers#howtopublish @kcopas Manuscript creation is a process better started on Pensoft's own website. At best this proposed button brings the user to Arpha where they still need to login and select their desired journal and article type. 

Instead of tightly coupling the IPT and its users to Pensoft, I believe users would appreciate an overview of journals where they can publish a data paper with supplementary information such as their APC, citation index, etc. 

For the above reasons I am closing this issue. If there are strong objections please continue to leave your comments for further consideration.

**Closed by kbraak** 2016-10-11 12:35 UTC

**Comment by dschigel** [comment] 2016-10-12 04:47
Hello,

As the issue is closed in Jira I will keep it red-flagged in my Outlook, copying Siro as he is working on data papers actively, and Kyle C for possible updates of the webpage identified below. FYI I won’t be able to work on this before 26 Oct.

Dmitry

**Comment by kcopas** [comment] 2016-10-12 06:13
Cited page will not exist as-is in the next version of the site. However, the data paper page will be a focus of attention. The point made here and any relevant content from the soon-to-be-deprecated page should find its way into the new data paper page that @timrobertson100 and @dnoesgaard will start on shortly.

**Comment by siro1** [comment] 2016-10-12 08:19
I agree with kbraak and kcopas. We have the content needed for the new data paper page. What we might want to do in future is to encourage other biodiversity data paper publishers we have identified to set up data paper writing tools similar to Pensoft's that supports Authoring, Reviewing, Publishing, Hosting, and Archiving.
