### ISSUE TITLE
IPT3: Public archives don't appear on the home page

### ISSUE THREAD

**Issue by timrobertson100** [gbif/ipt#2028] opened 2023-05-12 07:58 UTC
I created a Material core archive, published it, made it public but it did not appear in the IPT homepage table

**Comment by timrobertson100** [comment] 2023-05-12 08:04
It only becomes actually visible after a new publication. I presume this is per design so I'll close this.
It was not what I had expected as behaviour though - I expected that changing visibility would make the current one public.

**Comment by peterdesmet** [comment] 2023-05-12 08:17
I've also been caught by this. I think it is the expected behaviour, but it would help to warn users in the publishing dialog box that they are about to publish a private resource.

**Comment by peterdesmet** [comment] 2023-05-12 08:26
I suggest to rephrase some of the elements too:

<img width="506" alt="Screenshot 2023-05-12 at 10 24 16" src="https://github.com/gbif/ipt/assets/600993/e59b01c3-528c-48af-97df-0f3060ff9207">

- Combined the sentence "Before you publish, you can assist researchers using your data by summarizing what has changed in this version." with the text that is _in_ the text area.
- Remove "Do you still want to publish?" (odd before the text area) and change the buttons to `Cancel` and `Publish`.
- The sentence "If there have been scientifically significant changes to the resource since the last publication, you should cancel, assign this resource a new DOI, and then publish again." should ideally only be shown if the IPT is configured to mint DOIs

**Closed** 2023-05-30 11:58 UTC
