### ISSUE TITLE
Publication issues for multiple resources

### ISSUE THREAD

**Issue by dbloom** [gbif/ipt#2415] opened 2024-05-07 23:13 UTC
@mike-podolskiy90 Since we're having so much fun with the VertNet IPT today...

Two possibly related issues to report.

1. The LACM has been attempting to publish this [resource](https://ipt.vertnet.org/manage/resource?r=lacm_ento) (ironic in that it is the resource you thought issue #2414 described). The change was the addition of a Resource Relationship Extension, per my instructions to them. The result has been the locking of the resource with the message "Not started yet". This resource sat this way for approximately an hour before I was notified that they were having the issue. I logged in, was able to cancel the publication. I checked the new source file and the new extension mapping. All appear fine. When I attempt to publish, I get the same result.

I noted that there were only three other resources being run at that time, according to the registry monitor. So, I can't imagine that the infrastructure is the cause of the delay or hold.

2. Perhaps related, perhaps not. When I logged in to check on this resource I have noticed that none of the resources on this IPT that have scheduled monthly publications were completed. It appears that they have not been publishing, even when the auto-publishing is active, beginning April 27th and continues through today. I haven't looked at them all, but there could be as many as 160 or more resources affected (if you look, ignore all datasets with GGBN in the title - those have other issues I am almost finished solving).

One example is this [resource](https://ipt.vertnet.org/manage/resource?r=unr_egg), which appears to be in the middle of publishing, but the date of auto-publication was April 27th. Has it been trying to publish since then? I do not see it in the ingestion monitor. Some resources are like this one, most are not, but none of the affected resources have published when expected.

Any thoughts?

**Comment by mike-podolskiy90** [comment] 2024-05-08 07:19
Thank you for reporting the issues David!
I'll take a look, but I don't have many ideas. Do they use SQL sources? Maybe something stuck while querying the database.

**Comment by mike-podolskiy90** [comment] 2024-05-10 09:48
@dbloom The investigation may take some time. I couldn't find the cause of the problem. I'm off next week and won't be able to investigate further.

**Comment by MattBlissett** [comment] 2024-05-10 10:40
Mikhail asked me to look.

I tried publishing [LACM](https://ipt.vertnet.org/manage/resource?r=lacm_ento) and it succeeded without an error.

I also don't see non-GGBN auto-publishing failures, except [uwbm_invertpaleo](https://ipt.vertnet.org/manage/resource?r=uwbm_invertpaleo). 

Maybe the new version 3.0.4 (or simply the restart of the system to do the upgrade) has removed the problem. Let's see if they start to fail again in 7 days before closing this issue.

**Comment by dbloom** [comment] 2024-05-10 19:30
Thank you @MattBlissett 

Things look resolved on my end, too. I've set a reminder to check things for this issue next Thursday to confirm things have worked themselves out.

**Comment by dbloom** [comment] 2024-05-16 19:04
@mike-podolskiy90 @MattBlissett As promised, I've checked the IPT and it appears those resources with scheduled publication dates and times are working as intended.

Thanks for following along. Feel free to close this issue.

**Closed** 2024-05-19 12:46 UTC
