### ISSUE TITLE
The col DP mapping interface isn't what's expected

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#2529] opened 2024-09-24 13:23 UTC
Issue originally reported by @EstebanMH-SiB on the GBIF Helpdesk

They created a colDP dataset on an IPT Version 3.0.6 but when trying to map the data, the only options shown are the Darwin Core ones.
![image](https://github.com/user-attachments/assets/764b8628-0c14-4fc3-b4a4-eb061ea68abc)

If they choose a taxon Core, the dataset type becomes `Checklist`.
![image](https://github.com/user-attachments/assets/c5ee3d4d-7e73-4263-bced-c976b48c657d)

I couldn't reproduce the issue on our test IPT with the data I had. I am not sure what is happening.

**Comment by mike-podolskiy90** [comment] 2024-09-24 13:25
Thank you Marie.

Something is wrong with the handling of resource types. I'll have a look when I can

**Comment by mike-podolskiy90** [comment] 2024-09-24 13:50
There are no issues on the test IPT ipt.gbif.org though

**Comment by EstebanMH-SiB** [comment] 2024-09-24 14:09
Maybe it is because of our installed datapackage?
<img width="735" alt="image" src="https://github.com/user-attachments/assets/3c30e8cf-ffa0-4d87-b44e-4dda2c392644">

**Comment by mike-podolskiy90** [comment] 2024-09-24 17:16
Thanks @EstebanMH-SiB, I can't say right away. What if you try to create a new resource? Is it always like that?

**Comment by EstebanMH-SiB** [comment] 2024-09-24 18:15
Yes, it always change the type and do not let me map ColDP, even in our other IPTs in version 3.0.6:


https://github.com/user-attachments/assets/51932211-fdbf-4693-9477-b36d44684c3e

**Comment by mike-podolskiy90** [comment] 2024-09-25 12:47
@EstebanMH-SiB I can't reproduce that on test IPTs. This is something specific to your IPT I think. Would it be possible to give me access? Maybe I can figure it out

**Comment by mike-podolskiy90** [comment] 2024-09-30 09:12
@EstebanMH-SiB I've checked your IPT. Turned out, it's running in Production mode. ColDP is not in production yet and available only in Test mode. It won't work correctly in production mode right now. I'm not sure how you managed to install it.

**Comment by mike-podolskiy90** [comment] 2024-10-30 09:13
@EstebanMH-SiB I'm closing this issue. Please don't use ColDP in production yet - it might cause issues like this.

**Closed by mike-podolskiy90** 2024-10-30 09:13 UTC
Labels: Data Package : ColDP
