### ISSUE TITLE
Problems connecting to MySQL 5.7 databases

### ISSUE THREAD

**Issue by ben-norton** [gbif/ipt#1594] opened 2021-06-21 19:21 UTC
Removed

**Comment by ben-norton** [comment] 2021-06-21 19:22
Original issue was removed since it is specific to vertnet,

**Comment by MattBlissett** [comment] 2021-06-21 19:24
#1590 might be related.

**Comment by ben-norton** [comment] 2021-06-21 20:03
The mysqld.log file says 'Bad Handshake', which most likely means its related to the version of MySQL and the TLS connection, but it's hard to know. I have no trouble connecting to the remote database from my local PC.

**Comment by ben-norton** [comment] 2021-06-21 20:05
Maybe I was wrong about the issue being specific to vertnet. 
I can no longer make remote database connections to a MySQL database.The problem is consistent across all existing database connections. Therefore, this seems to be a recent development (over the past 1-2 months). 
 The error is encountered when I click Analyze under connect to database:
 Couldnt create new external datasource connection with JDBC Class=com.mysql.jdbc.Driver, URL=jdbc:mysql://nakhlite.naturalsciences.org/nakhlite_aves_dwc, user=nakhlite_dwcdbu. Error: Communications link failure The last packet successfully received from the server was 2 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.
 
I checked the mysqld.log file. It simple states the following:
 'Bad Handshake'

I discovered the problem after attempting to refresh an existing dataset. The connection failed, so I went to the connection clicked edit then analyze.

**Comment by MattBlissett** [comment] 2021-06-22 11:49
IPT version 2.4.1 was released in September 2020, and upgraded the MySQL JDBC connector from 5.1.44 to 8.0.16.  Version 2.4.2 was released a few days later.

I can reproduce the problem with the Docker builds (version 2.4.0 can connect to MySQL 5.7, but version 2.4.2 cannot), but not running from the development environment (Maven), which is very odd.

With the current 2.5.x release, which we're working on at the moment, connector version 8.0.25 is used.  This works, although I don't see anything in the MySQL [changelog](https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-25.html) for the intervening versions to suggest a bug was fixed.

You could test with the [development version](https://repository.gbif.org/service/rest/repository/browse/snapshots/org/gbif/ipt/2.5.0-SNAPSHOT/) (currently in [here](https://repository.gbif.org/service/rest/repository/browse/snapshots/org/gbif/ipt/2.5.0-SNAPSHOT/2.5.0-20210622.071307-109/) though newer builds will appear), but we have not yet prepared a release candidate, or tested the upgrade procedure, so please back up your data directory before trying this.

**Comment by ben-norton** [comment] 2021-06-22 16:04
Thanks for your prompt response regarding the issue. I tried another MySQL database server this morning, running in an entirely separate environment using MySQL 5.7.29. To summarize, I've encountered the problem with MySQL 5.733, 5.732, and 5.7.29. I've whitelisted every IP address and disabled firewalls.
I'll see what I can do regarding testing. I currently utilize the IPT instance at VertNET. So I'll need to set up the environment first.

**Comment by dbloom** [comment] 2021-06-29 16:34
Late to the party here. To start, I have more than 100 direct dbase connections running through the VertNet IPT, and none are in error at the moment. I wonder, however, if this could be a firewall issue on our side? Our server is based at the Field Museum in Chicago. I have, in the past, had to open up the Field's firewalls to establish some connections. Is that worth looking into here?

**Comment by MattBlissett** [comment] 2021-06-30 09:36
We don't have a great error message from the IPT (I'm not sure if that's the IPT's fault, or the MySQL connector).  It's possible for a firewall block to be causing an error like this, but it would be a strange firewall configuration — the MySQL server is receiving something, since it logs "Bad connection" itself.

You could use the MySQL CLI client (if it's installed on the server), or something like nc: `nc -v nakhlite.naturalsciences.org 3306` (I get "Host ... is not allowed to connect to this MySQL server", showing there is no firewall between my computer and this MySQL server) to see if there's an additional firewall in the way.

Ben: I've set up a 2.5.0-RC1 IPT for you on GBIF's network, which you may use to test. (See your email for the password.)

**Comment by MattBlissett** [comment] 2021-08-20 09:51
Ben tested and this works in the 2.5.0-RC1, I forgot to update this issue.

**Closed by MattBlissett** 2021-08-20 09:51 UTC
