### ISSUE TITLE
Archive validator inside IPT misses errors found by online 'Darwin Core Archive Validator'

### ISSUE THREAD

**Issue by meliezer** [gbif/ipt#1243] opened 2015-12-09 16:51 UTC
Hello,
an example: duplicate id errors, missed by IPT 2.3.2.

For now, I recheck with http://tools.gbif.org/dwca-validator/validate.do after the successful IPT publication.

Regards,
Menashè

**Comment by kbraak** [comment] 2015-12-09 18:05
Menashè, is this a duplicate of issue #1244 you also opened?

**Comment by meliezer** [comment] 2015-12-10 09:47
No, it's not. In the case of issue #1244 the archive cannot be created, hence cannot be validated by the online validator. In the current issue the core is occurrence core.

**Comment by kbraak** [comment] 2015-12-10 12:27
Ok. Can you please provide me with enough detail (instructions, files) to understand and reproduce this issue? Thanks

**Comment by meliezer** [comment] 2015-12-15 11:52
Sent by email.

**Comment by kbraak** [comment] 2015-12-15 14:35
Issue address in new issue #1246, closing.

**Closed by kbraak** 2015-12-15 14:35 UTC
Labels: bug, Type-Defect, Won't-fix
