### ISSUE TITLE
Connect to gzip/zip file to republish as alternative to db connection

### ISSUE THREAD

**Issue by dshorthouse** [gbif/ipt#1193] opened 2015-09-03 03:08 UTC
As an alternative to connecting to a recognized db that has drivers integrated in the IPT, connecting to a directory or URL to pull a zip/gzip file containing data for a resource would be very helpful. This would be particularly useful in the distributed Canadensys network because it would eliminate the need for manual re-uploaded of refreshed data. It would also be useful for databases that do not have client drivers for Linux, but can be scripted to produce exports (eg FileMaker).

**Comment by kbraak** [comment] 2015-09-14 10:18
Duplicate of Issue #790.

Please note that in 2011/12 a thorough investigation into connecting the IPT to FileMaker was done. It was deemed unusable, however, it might be worth investigating again should there have been improvements made to the driver in the last few years. For more information about this investigation, please see Issues #788 and #789.

For other readers' benefit, instructions on how to connect the IPT to other databases using their JDBC driver can be found in [this](https://github.com/gbif/ipt/wiki/IPT2DatabaseConnection.wiki) wiki page.

**Closed by kbraak** 2015-09-14 10:18 UTC
Labels: duplicate
