### ISSUE TITLE
Minor issue: Link to github IPT user manual would be nice, especially for new users of the IPT

### ISSUE THREAD

**Issue by DanBIF** [gbif/ipt#1219] opened 2015-10-15 07:10 UTC
Change the old link at bottom of IPT UI (http://code.google.com/p/gbif-providertoolkit/wiki/IPT2ManualNotes) to the valid one https://github.com/gbif/ipt/wiki

**Comment by kbraak** [comment] 2016-10-11 10:03
Fixed in following commit: https://github.com/gbif/ipt/commit/ad53401ca8d3b7cabe09cb859d442c8722c20c86 Closing issue.

**Closed by kbraak** 2016-10-11 10:03 UTC
Labels: bug, Component-UI, Priority-Critical, Type-Defect

**Comment by kbraak** [comment] 2016-12-22 09:10
Duplicate of #1279
