### ISSUE TITLE
Updating dataset metadata in IPT fails

### ISSUE THREAD

**Issue by jlegind** [gbif/ipt#1519] opened 2020-12-03 09:46 UTC
Authors of one of the West of Urals data papers, struggle to add or remove resource creators, they have about 20 of those. Refreshing / restarting does not seem to help – GBIF.ru people tried and were not able to help.

IPT = http://gbif.ru:8080/ipt/rss.do 
Might be related to https://github.com/gbif/ipt/issues/1511

![ipt_screen](https://user-images.githubusercontent.com/5330066/100992610-ac597180-3554-11eb-885b-bf657f1cae83.png)

**Comment by timrobertson100** [comment] 2020-12-03 09:52
@jlegind - can you please ask them for an admin account on their IPT and try and verify and help diagnose the cause? There are no known issues around this, and I see it works in ipt.gbif.org. Please keep an eye on JS errors in the browser.

**Comment by timrobertson100** [comment] 2021-04-28 10:11
Is this still an issue for the publisher please?

**Comment by jlegind** [comment] 2021-05-20 12:48
Hi , we just had a Macedonian publisher write to helpdesk about a similar issue.

**Comment by MattBlissett** [comment] 2021-06-22 10:13
The Macedonian publisher wrote:

> On our IPT we can't add more than 1 resource creator or resource contact. By clicking Add new resource contact it only refreshes the page and doesn't provide additional section for new creator/contact.

I wonder if there's a bug in the Javascript. 

![image](https://user-images.githubusercontent.com/583320/122906788-d2a8f800-d352-11eb-81f0-3fd42d9d9b81.png)

When you click "Remove this ..." it adds an additional click event to the remaining "Remove" links.  (I have removed one block here, so there are two click links, plus the third which I don't know the purpose of.)

I'm still able to add/remove 20 resource creators, but it could be affected by different browsers.

**Comment by sl808** [comment] 2021-06-29 13:55
Hello,
Now I see that this is still open issue.
However, we still face this problem. Matt Blissett, suggested to try another web browser but we already tried that with almost any web browser and it does solves the problem. Also, we tried with a different machine on different OS, and nothing solves our problem. :(
We are currently using IPT version 2.4.0, but planing to update to 2.4.2 during this week. 
Regarding the update, we might need some help, for example do we need to backup just the published data or there is some other kind of backup that covers the whole IPT installation? 
If there is some tutorial on how to update the IPT sharing would be much appreciated.
Thank you

**Comment by MattBlissett** [comment] 2021-06-30 10:43
Hi,

The upgrade instructions are here: https://ipt.gbif.org/manual/en/ipt/2.4/release-notes

You need to back up your IPT data directory.  It's shown on the Administration → IPT Settings page.  (Hopefully you are backing this up already, or backing up the whole server.)

The WAR file download for version 2.4.2 is here: https://repository.gbif.org/content/groups/gbif/org/gbif/ipt/2.4.2/ipt-2.4.2.war

----

Regarding the problem, could you go to the page where you were trying to add a new resource contact and open the web browser's developer tools (Menu → More Tools → [Web] Developer Tools; or you can usually just press "F12" on Windows/Linux).  Open the "Console" tab, and then try "Add New Resource Contact" etc to repeat the problem.  If any new lines appear in the "Console" tab, please paste/screenshot them here.

Thanks

**Comment by sl808** [comment] 2021-07-06 12:00
So, after many many spent hours working on this, today I found the bug that was causing this.
In the street address field I was using double quotes, and that seemed to be the problem. I hope it is an easy fix and it will be solved in the next IPT version.

**Comment by mike-podolskiy90** [comment] 2021-07-12 13:24
This is a double quotes issue indeed. Thank you for the comment @sl808 .
I added a fix to this one, will be included in the next release (2.5.0-RC2)

**Closed by mike-podolskiy90** 2021-07-12 13:24 UTC
