### ISSUE TITLE
figures in metdata

### ISSUE THREAD

**Issue by DimEvil** [gbif/ipt#1326] opened 2017-03-09 08:48 UTC
What would it be nice to have (or to be able to have) figures in the metadata.

**Comment by dschigel** [comment] 2017-03-09 09:14
Like figures illustrating sampling methods? Note that licenses and rights for images are different from those for text bits @ahahn-gbif

**Comment by ahahn-gbif** [comment] 2017-03-09 09:27
Could you be a bit more specific, @DimEvil? Figures as in numbers, or as in images? Documenting / indicating what?

**Comment by kbraak** [comment] 2017-03-09 09:35
Closing as duplicate of reopened issue https://github.com/gbif/ipt/issues/971, which has more details and rationale behind this proposed enhancement.

**Closed by kbraak** 2017-03-09 09:35 UTC
