### ISSUE TITLE
IPT upgrade from 2.3.2 to 2.3.4

### ISSUE THREAD

**Issue by crebollobr** [gbif/ipt#1331] opened 2017-03-20 16:15 UTC
Just upgrade

**Comment by kbraak** [comment] 2017-03-20 16:39
@crebollobr can you please provide some more detail to this issue? Thanks

**Comment by crebollobr** [comment] 2017-03-20 18:57
Hello,
I Have done upgrades 2.2.1, 2.3-SNAPSHOT ( some problem in 2.3.0 ), 2.3.1, 2.3.2 without problem.
My environment configuration has been upgrade to. Now:
Java JDK 1.8.0_121
Apache tomcat 8.5.12

I have clicked in link to send the problem but i gess no another information was send.
After upgrade, the site start to error 500

HTTP Status 500 – Internal Server Error

Type Exception Report

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

java.lang.NullPointerException
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	org.gbif.ipt.struts2.ResourceSessionInterceptor.intercept(ResourceSessionInterceptor.java:41)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	org.apache.struts2.impl.StrutsActionProxy.execute(StrutsActionProxy.java:54)
	org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:575)
	org.apache.struts2.dispatcher.ng.ExecuteOperations.executeAction(ExecuteOperations.java:81)
	org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:99)
	org.gbif.ipt.struts2.ResponseHeaderFilter.doFilter(ResponseHeaderFilter.java:53)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
	org.gbif.ws.server.filter.XSSFilter.doFilter(XSSFilter.java:48)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	org.gbif.ipt.struts2.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:43)
	com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)

Note The full stack trace of the root cause is available in the server logs.
Apache Tomcat/8.5.12

ipt_log.tar log ipt folder folders logs
tomcat_log.tar.gz apache folder logs


[tomcat_log.tar.gz](https://github.com/gbif/ipt/files/856039/tomcat_log.tar.gz)


[ip_log.tar.gz](https://github.com/gbif/ipt/files/856041/ip_log.tar.gz)

**Comment by crebollobr** [comment] 2017-03-20 18:58
I have a backup of data folder. And I have back the 2.3.2 version

**Comment by kbraak** [comment] 2017-03-21 11:31
To eliminate your firewall as the root of this error, can you please try to follow the instructions here: https://lists.gbif.org/pipermail/ipt/2017-March/000674.html ? I look forward to hearing the result. Thanks.

**Comment by crebollobr** [comment] 2017-03-21 12:52
Hello, 
the curl command have failed with https. We do not have firewall blocking this host. I have google it and same problems with curl are about update some system packages. I have upgraded host and the curls commands are working now. But upgrade did not work for both 2.3.3 and 2.3.4.

[data_logs.tar.gz](https://github.com/gbif/ipt/files/858134/data_logs.tar.gz)
[tomcat_logs.tar.gz](https://github.com/gbif/ipt/files/858135/tomcat_logs.tar.gz)

**Comment by crebollobr** [comment] 2017-03-21 12:53
Sorry wrong button

**Comment by kbraak** [comment] 2017-03-21 16:16
What operating system are you using, and have you tried restarting Tomcat?

**Comment by crebollobr** [comment] 2017-03-21 17:53
Hello,
CentOS release 6.8 (Final)
Yes a have tried restart the tomcat before update and after update.

**Comment by kbraak** [comment] 2017-03-22 13:30
I have several installs working on CentOS Linux 7 (Core) running Tomcat 7 and Java 8. 

Can you please try checking, if a brand new installation of 2.3.4 works on your server?  This will isolate the problem is to do with your server environment, or to do with your existing data directory. Please remember to backup your IPT data directory before trying this. Thanks.

**Comment by kbraak** [comment] 2017-03-24 18:40
@crebollobr - any update on fixing this issue please? Thanks.

**Comment by kbraak** [comment] 2017-03-27 12:54
@crebollobr can I please let me know if your problem has gone away, and if I can close this issue now? Thanks.

**Comment by kbraak** [comment] 2017-10-16 16:25
Closing issue. If problems persist @crebollobr please reopen a new issue. Thanks.

**Closed by kbraak** 2017-10-16 16:25 UTC
