### ISSUE TITLE
No 'Yes' button in Registration dialog

### ISSUE THREAD

**Issue by andrejjh** [gbif/ipt#1240] opened 2015-12-07 09:26 UTC
On IPT Version 2.3.2-rea67259,
When trying to register a newly created ressource to GBIF, 
the registration dialog appears with 'No' button only.
After clicking the 'Confirm' checkbox, the 'Yes' button does not appear...registration in NOT POSSIBLE using Chrome Version 47.0.2526.73 (64-bit) on Mac OSX.

![register](https://cloud.githubusercontent.com/assets/3941677/11623389/e5c37a18-9ccc-11e5-9ecc-36057fd2d489.png)
I tried to register the same ressource with SAFARI, the 'YES' button appeared as expected.

**Comment by kbraak** [comment] 2015-12-07 15:26
Thanks for reporting this issue André. Can you please try clearing your cache, to see if it fixes the problem?

**Comment by andrejjh** [comment] 2015-12-08 16:14
Unfortunately, I already registered that resource through Safari.
So I can't easily retry with Chrome+ cleaned cache.
I'll let you know when I try to register another resource.

**Comment by kbraak** [comment] 2016-10-12 16:10
@andrejjh Can I please check if you ever encountered this issue again? Or can I close it now? Thanks

**Comment by kbraak** [comment] 2016-11-01 08:07
Cannot reproduce. Fortunately this was only reported one time since December 2015. Closing issue.

**Closed by kbraak** 2016-11-01 08:07 UTC
Labels: bug, Component-UI, Priority-High, Type-Defect, Won't-fix
