### ISSUE TITLE
Add an option to load metadata fromeml.xml

### ISSUE THREAD

**Issue by meliezer** [gbif/ipt#1242] opened 2015-12-09 16:41 UTC
Hello,
In case of similar metadata, it would be nice having the option to import eml.xml to the new project.
An example: converting an existing occurrence core resource to a project with the new event core.
Importing the all archive is not relevant in this example.
Before importing, the user should be warned that all current metdata settings will be overwrited by the imported eml.xml.
For now, users with access to the data folder can replace the existing eml.xml file, but not everyone have such access.

Regards,
Menashè

**Comment by kbraak** [comment] 2015-12-09 17:18
Thanks for reporting this issue. I believe the feature you are requesting is a duplicate of issue #955. 

You can also create a new resource using only the metadata file. For instructions, see [this section](https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#upload-a-metadata-file) of the user manual.

**Closed by kbraak** 2015-12-09 17:18 UTC
