### ISSUE TITLE
Migrating to 2.3.3 Home page display stack error

### ISSUE THREAD

**Issue by simoncha** [gbif/ipt#1322] opened 2017-02-23 09:14 UTC
Hi,

Migration to 2.3. almost completed, most dataset seems fine :-)

Still an ugly message on the home page :
```

Technical Details

java.lang.NullPointerException at org.gbif.ipt.config.DataDir.resourceEmlFile(DataDir.java:220) at org.gbif.ipt.action.portal.HomeAction.prepare(HomeAction.java:61) at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:167) at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:164) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:189) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at com.opensymphony.xwork2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:140) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.gbif.ipt.struts2.RedirectMessageInterceptor.doIntercept(RedirectMessageInterceptor.java:120) at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.gbif.ipt.struts2.PrivateDeletedResourceInterceptor.intercept(PrivateDeletedResourceInterceptor.java:82) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.gbif.ipt.struts2.SetupAndCancelInterceptor.intercept(SetupAndCancelInterceptor.java:84) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.gbif.ipt.struts2.ResourceSessionInterceptor.intercept(ResourceSessionInterceptor.java:41) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.apache.struts2.impl.StrutsActionProxy.execute(StrutsActionProxy.java:54) at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:575) at org.apache.struts2.dispatcher.ng.ExecuteOperations.executeAction(ExecuteOperations.java:81) at org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:99) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.gbif.ipt.struts2.ResponseHeaderFilter.doFilter(ResponseHeaderFilter.java:53) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66) at org.gbif.ws.server.filter.XSSFilter.doFilter(XSSFilter.java:48) at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) at org.gbif.ipt.struts2.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:43) at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:240) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:745)
 
```

Any ideas ?

**Comment by kbraak** [comment] 2017-02-24 13:24
Thanks Simon, 

First can you please try restarting Tomcat? 

If that doesn't fix this problem, we then need to identify the resource(s) responsible for triggering this error. To do this, I would recommend turning on debugging mode in your IPT settings and monitoring the log messages for clues. Feel free to send me your IPT's log files and I can help in debugging. Thanks.

**Comment by simoncha** [comment] 2017-02-27 16:39
Restarting Tomcat does not help. I will upload some log file soon ...

**Comment by simoncha** [comment] 2017-02-27 16:54
[debug.zip](https://github.com/gbif/ipt/files/804362/debug.zip)

Here is the log of consulting the resource mnhn-f , restarting tomcat, refreshing mnhn-f page and going on home page

I am aware of problem on mnhn-zo dataset. I do not think it is related to this issue as It already occured on 2.1 version. Anyway we will fix the data soon.

Regards,

**Comment by kbraak** [comment] 2017-02-27 19:37
Thanks Simon, 

Please try removing (backing up somewhere safe) the following resource directory /apps/ipt/resources/**clf** and then try restarting Tomcat to see if the NPE is fixed. Looking at http://collections.mnhn.fr/ipt/resource?r=clf this appears to be an invalid/incomplete resource that can be deleted. 37 out of your IPT's 41 datasets are [registered with GBIF](http://www.gbif.org/installation/86c2834b-fcd6-418d-9b32-aca45110a0fe/datasets), therefore if there are other invalid/incomplete resources you should try removing these also. Please let me know if this works, thanks.

**Comment by simoncha** [comment] 2017-02-28 08:31
Much better without CLF :-)
I am going to fix that resource
Still not listing resources on home page but it was already the case with previous version and we can live with RSS feed

Thank you very much Kyle

**Comment by kbraak** [comment] 2017-02-28 08:46
Great news! 

You're very welcome. 

We can easily fix your home page. The problem is that you have newline characters in at least 3 resources' titles. For each resource you need to clean the title and republish it, which will fix the problem. Below is a screenshot of the affected resources. 

![screen shot 2017-02-28 at 09 36 54](https://cloud.githubusercontent.com/assets/5981100/23397648/b48a79b8-fd99-11e6-8eb3-2cf00da37383.png)
![screen shot 2017-02-28 at 09 37 13](https://cloud.githubusercontent.com/assets/5981100/23397646/b48a305c-fd99-11e6-9144-2995f9ac687e.png)
![screen shot 2017-02-28 at 09 37 51](https://cloud.githubusercontent.com/assets/5981100/23397647/b48a673e-fd99-11e6-988c-db74754d4b9c.png)

If the home page still doesn't appear, there may be more such cases you need to fix. To diagnose them, you can open the Developer/Javascript tools in Chome for example - see below. 

![screen shot 2017-02-28 at 09 42 43](https://cloud.githubusercontent.com/assets/5981100/23397909/aa7d94e0-fd9a-11e6-9348-c87589dadc82.png)

Please let me know if this fixes the home page, thanks.

**Comment by kbraak** [comment] 2017-02-28 15:41
Thanks @simoncha. I have transferred your feedback to issue https://github.com/gbif/ipt/issues/1320 and will now close this issue.

**Closed by kbraak** 2017-02-28 15:41 UTC
Labels: bug, Type-Defect
