### ISSUE TITLE
No 'Add source' button 

### ISSUE THREAD

**Issue by andrejjh** [gbif/ipt#1234] opened 2015-12-02 15:07 UTC
I'm using IPT Version 2.3.2-rea67259, trying to add a new ressource.
After selecting a source file, the expected 'AddSource' button does not appear. (see screenshot)
![ipt](https://cloud.githubusercontent.com/assets/3941677/11534403/dad16064-990e-11e5-938d-b88d432c958f.png)
Browser Chrome Version 47.0.2526.73 (64-bit) on MacOSX El Captain.

**Comment by kbraak** [comment] 2015-12-02 15:11
Thanks for reporting the issue. It looks like you forgot the screenshot though. 

Still need to try and reproduce this myself.

**Comment by kbraak** [comment] 2016-10-11 09:58
Dear André, I'm a Chrome user on Mac myself but have never been able to reproduce this problem. Closing as won't fix, but please create a new issue if it reappears. Thanks

**Closed by kbraak** 2016-10-11 09:58 UTC
Labels: bug, Type-Defect, Won't-fix
