### ISSUE TITLE
Footer overlaps with mapping on

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1826] opened 2022-09-12 13:58 UTC
_This issue relates to using IPT for publishing [Camtrap DP](https://tdwg.github.io/camtrap-dp/) and is not applicable to production IPTs._

On the mapping page (`schemaMapping.do`) the footer overlaps and hides mapping fields:

![Mapping-Source-Data](https://user-images.githubusercontent.com/600993/189673146-58fb93f3-14d9-49ed-accc-eb4b9378b232.png)

**Comment by mike-podolskiy90** [comment] 2022-10-04 11:28
Couldn't reproduce that, it seems it was fixed in the 2.6

**Comment by MattBlissett** [comment] 2022-10-04 12:04
Try https://ipt3.gbif-uat.org/manage/schemaMapping.do?r=camtrap-test&id=http%3A%2F%2Frs.gbif.org%2Fschemas%2Fcamtrap-dp&mid=2 in Firefox.

**Comment by mike-podolskiy90** [comment] 2022-10-04 12:57
Redeployed new versions there, Firefox is fine now too. Closing this

**Comment by peterdesmet** [comment] 2023-02-27 09:02
This issue is still present or returned on ipt3.gbif-uat.org. Maybe the deployment there has not caught up with 8a10381?

**Comment by mike-podolskiy90** [comment] 2023-02-27 09:38
Thanks @peterdesmet 
I'll investigate

**Comment by mike-podolskiy90** [comment] 2023-03-02 08:25
I removed some redundant css and don't experience this issue.
@peterdesmet Could you confirm please

**Closed** 2023-03-02 08:31 UTC
Labels: DataPackage-Camtrap, DataPackage
