### ISSUE TITLE
Datasets displaying a incorrect DOI

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/ipt#1940] opened 2022-12-29 05:35 UTC
There are two datasets that are displaying an incorrect DOI and not the DOI that is in our IPT.

- [Monitoreo de peces, calidad del agua y caracterización de la comunidad hidrobiológica en los ríos Cucuana y San Marcos, área de influencia de la Central Hidroeléctrica del río Cucuana](https://www.gbif.org/dataset/b4cfbb59-5194-4e1a-aa55-fcc5e1d1e69f) should have this DOI [https://doi.org/10.15472/4vnoip](https://doi.org/10.15472/4vnoip).
- [Artrópodos de los Parques Ecológicos Distritales de Montaña](https://www.gbif.org/dataset/865c11e6-8d75-4acb-8f09-5d909e08ed6b) should have this DOI [https://doi.org/10.15472/cwrg3e](https://doi.org/10.15472/cwrg3e).

Thanks in advance and have a happy new year

Edit: As an additional information, the DOI that resources are showing is a DOI from another resource of the same organization that was published the same day, so maybe it was some sort of cable crossings

**Comment by mike-podolskiy90** [comment] 2024-11-07 10:34
Unfortunately I don't know the cause of the problem. If it happens again, let me know and please don't change the resource so we can find the cause.

Also, I would strongly recommend to update your IPT to the latest 3.1.0 version (or at least 3.0.6).

Closing this for now

**Closed by mike-podolskiy90** 2024-11-07 10:34 UTC
