### ISSUE TITLE
Slow validation for large dataset when publishing in IPT (67 M records - takes 10 days+)

### ISSUE THREAD

**Issue by mskyttner** [gbif/ipt#1450] opened 2019-05-15 13:53 UTC
This could be related to #1062 and currently is an issue in our production environment which hasn't published updates for a while for the Artportalen data. 

We're currently attempting a workaround which avoids to use IPT for publishing and instead does this from the command line, after speaking to people in GBIF Norway who have used this approach in the past for their larger datasets when publishing and running into similar performance issues.

The problem we have is that the validation in IPT when publishing the Artportalen dataset is slow and takes more than 10 days and then doesn't complete.

Using a separate clean box with the latest (dockerized) stable IPT version we compared and also get the same slow validation of the occurrenceID column for this dataset. When publishing from that IPT instance, a sorting of the OccurrenceID that calls out to gnu sort gradually also here grinds to a halt, becoming slower and slower as the number of records increase. It completes however, and doesn't crash like our production deployment of IPT, but it its still too slow for practical use.

So we have some questions that came up when trying to work on this issue.

The first question is if and why the sorting on the occurrenceID is required? Does the sorting of the occurrenceID aim at making sure that the submitted archive is sorted? Is that a requirement for GBIF to process it? Or is it used as a step on the way towards verifying presence and uniqueness of occurrenceID identifiers?

Another question is related to disk space. When testing with gradually larger data ie using a "select * from artdata limit 1 million, 2 million, 5 million and 67 million" approach, we get exponentially increasing validation time as well as a lot of files on disk eating considerable space.

The disk space used is big - 5.7 G for the dwca.zip, 66 GB for the uncompressed archive's tsv file and in addition to this also a whole lof of space also eaten by various file segments created by gnu sort during the sorting of the occurrenceID. It seems publication using the IPT of a 5.7G dwca.zip requires several hundreds of GBs of temp files currently. 

With the existing IPT approach of calling out to gnu sort, would it be possible to pull out just the column for occurrenceIDs into a separate smaller file and sort it separately (if needed) to save on the temp files and disk space? Then perhaps all of the other columns wouldn't need to be dragged around and serialized to disk? A separate later step calling "gnu join" with the sorted single column data comining it with the original file could perhaps be faster to create the new sorted archive, if it is required to have the whole archive sorted before submitting it?

I'm not sure what is causing the slowness and when testing validation of very similar data it looks like we should expect significantly faster sorting. Some tests and benchmarks are attached.

This in-memory approach in R checks for uniqueness and presence in about 2 seconds for 70 M strings of 41 characters, and uses less than 2 minutes for a radix sort:

[check_occurrenceid.pdf](https://github.com/gbif/ipt/files/3182719/check_occurrenceid.pdf)

This bash approach with only three columns for 67 M strings uses files on disk and also takes a few minutes:

[check_occurrenceid_bash.pdf](https://github.com/gbif/ipt/files/3182729/check_occurrenceid_bash.pdf)

We haven't been able to figure out where the slowness comes from but it seems to be exponential and the gnu sort would probably not be so slow if it didn't have to shuffle around all of those columns that the Artportalen dataset has?

A  test using Apache Spark, converting the Artportalen dwca-zip into a parquet file and running some validation tests also takes somewhere in the range of a few seconds up to at the most five minutes for hopefully equivalent validation tests, and while this approach uses less disk space - the parquet file is around 3.7 GB which is smaller than the dwca-zip - it should scale well to any size dataset (which the faster inmemory sort maybe wouldn't). 

Here is an attempt to provide what is needed to replicate this test using Apache Spark through the sparklyr library:

```r
library(sparklyr)
library(dplyr)

# first install spark 2.40 hadoop 2.7 with sparklyr::spark_install()

Sys.setenv("SPARK_MEM" = "12g")

config <- spark_config()
config$`sparklyr.shell.driver-memory` <- '12G'
config$`sparklyr.shell.executor-memory` <- '4G'
config$sparklyr.defaultPackages <- "com.datastax.spark:spark-cassandra-connector_2.11:2.0.0-M3"
config$spark.cassandra.cassandra.host <- "localhost"
config$spark.driver.maxResultSize <- "4G"
config$spark.executor.cores <- 3

# is pushdown option TRUE?

sc <- spark_connect(master = "local", config = config)

# for this connection, load all records

system.time(
  spark_read_csv(sc, memory = FALSE,
    name = "artdata", path = "file:///home/roger/artdata/artdata.tsv", delimiter = "\t")
)

#user   system  elapsed 
#6.154    7.060 1559.874 

# generate a parquet file based on the dataframe above

system.time(
  spark_write_parquet(
    tbl(sc, "artdata"),  
    "file:///home/roger/artdata/artdata.parquet")
)

#user   system  elapsed 
#14.634   16.586 3816.375 

# the parquet-file is 3.8 GB on disk, smaller than the zip

spark_tbl_handle <- spark_read_parquet(sc, memory = FALSE,
  "artdata", "file:///home/roger/artdata/artdata.parquet")


has_valid_bor <- function() {
  
  bor <- 
    spark_tbl_handle %>%
    count(basisOfRecord) %>%
    collect() %>%
    mutate(is_ok = basisOfRecord %in% c(
        "humanobservation", 
        "machineobservation"
      )
    )

  bor %>% pull(is_ok) %>% all
}

n_rowcount <- function() {
  
  spark_tbl_handle %>%
  summarise(n = n()) %>%
  pull(n)

}


has_valid_id <- function() {
  
  ids <- 
    spark_tbl_handle %>%
    count(occurrenceID) %>%
    filter(n > 1, is.na(occurrenceID)) %>%
    collect()
  
  nrow(ids) == 0
  
}


system.time(
  has_valid_bor()
)

system.time(
  has_valid_id()
)

system.time(
  n_rowcount()
)

sort_artdata <- function() {
  spark_tbl_handle %>%
  arrange(occurrenceID) %>%
  head(10) %>%
  collect()
}

system.time(
  sort_artdata()
)

# sorting in spark takes about 5 minutes...
#user  system elapsed 
#3.182   1.370 282.698



src_tbls(sc)

#tbl_cache(sc, "artdata")

spark_disconnect(sc)
```

**Comment by timrobertson100** [comment] 2019-05-16 15:30
> The first question is if and why the sorting on the occurrenceID is required? 

It was intended to be a memory efficient way to check for uniqueness and referential integrity for extensions. When the IPT was designed it was to allow people to run with `-Xmx256m`.

>Does the sorting of the occurrenceID aim at making sure that the submitted archive is sorted?

No

> Is that a requirement for GBIF to process it? 

No

> Or is it used as a step on the way towards verifying presence and uniqueness of occurrenceID identifiers?

Yes

> Another question is related to disk space. When testing with gradually larger data ie using a "select * from artdata limit 1 million, 2 million, 5 million and 67 million" approach, we get exponentially increasing validation time as well as a lot of files on disk eating considerable space.
The disk space used is big - 5.7 G for the dwca.zip, 66 GB for the uncompressed archive's tsv file and in addition to this also a whole lof of space also eaten by various file segments created by gnu sort during the sorting of the occurrenceID. It seems publication using the IPT of a 5.7G dwca.zip requires several hundreds of GBs of temp files currently.

Can you please provide us the source data on a URL so we can diagnose in another environment? 

(The spark approach is similar to GBIF.org processing by the way. The IPT was written long before Spark and R existed though... I'd be surprised if a native linux sort didn't work out though)

**Comment by MattBlissett** [comment] 2019-05-16 16:18
> Can you please provide us the source data on a URL so we can diagnose in another environment?

I assumed the most recent successful publication of Artdata from http://www.gbif.se/ipt/resource?r=artdata was good enough. I've left it running on my desktop.

**Comment by timrobertson100** [comment] 2019-05-16 16:42
What flavour of linux do you run this on please @mskyttner ?

**Comment by mskyttner** [comment] 2019-05-16 17:11
I think that the most recent successful publication of Artdata should be good for the test. We were using a query to the mysql db where we have the latest version of the dataset which does a "select * from artdata" which creates a 66 GB text file with the occurrence data.

The production environment is running Ubuntu and the sed and gnu sort versions there were not the latest but fairly up to date. We can give more detail on that if needed, tomorrow. This is where the 10+ days of validating is occurring that never completes.

The other comparison test was run on a up-to-date Manjaro linux with a single stable IPT from here https://github.com/bioatlas/ipt-docker running without virtualization but inside of an Alpine Linux container with the coreutils specifically installed to get an up to date version of the gnu sort. The logs there indicate that the gnu sort rather than internal Java sorting is being used, so the slowness comes from elsewhere. On this box the operation completes after approximately 10 days. This box has a spinning disk which is not very fast and was showing audibly high io activity throughout the validation process.

**Comment by mskyttner** [comment] 2019-05-17 09:42
The dev box details: Manjaro with 4.19. 36-1 kernel, Intel i5-4300U @ 1900 GHz w 4 CPUs, 15 GB of RAM, 440 GB of disk with a sluggish spinning disk (cached reads 7825 MB/sec, buffered reads 119 MB/sec from "hdparm -Tt /dev/sda" and perhaps more importantly a modest write speed of 144 MB/s as reported from "dd"). The gnu sort version used is 8.30 from GNU coreutils running inside an Alpine Linux container running under docker version 18.09-5-ce which is using the overlay2 driver against an extfs backing filesystem. This same box ran the Apache Spark tests and completed the IPT validation in 10 days without getting stuck.

The production box details: This is hosted on-premise in the museum, it is Ubuntu v 16.04.6 with kernel 3.13.0, AMD 2.3 GHz with 4 CPU running inside a VMWare hypervisor, gnu sort is 8.21, sed v 4.2.2 and regarding disk io speed,it appears the disk which is mounted over nfs with settings providing from the museum's IT department is sluggish compared to the dev box and especially compared to a cloud server. The production box disk io metrics reported from "sudo bash -c "sync; dd if=/dev/urandom of=tempfile bs=1M count=1024; sync" is 3.8 MB/s and we get 171 MB/s on a comparable cloud server. Metrics from ioping is 4.0 MiB/s for the on-premise production box while the cloud server we compare with gives 13.3 MiB/s for an equivalent nfs share mount ("sudo ioping -c 10 /media/nfsshare/"). 

I have raised the issue with what seems comparatively slow disk io with the IT-department of the museum. It might play a big(?) role in our slow validation times we see for the on-premise production environment where the gbif.se/ipt currently is deployed.

**Comment by MattBlissett** [comment] 2019-05-20 10:38
Using the current snapshot version of the IPT, publication took 3½ hours:

```
Thu May 16 17:14:38 2019: INFO  Start writing data file for Darwin Core Occurrence
Thu May 16 19:07:11 2019: INFO  Data file written for Darwin Core Occurrence with 64969248 records and 169 columns
Thu May 16 19:07:11 2019: INFO  All data files completed
Thu May 16 19:07:11 2019: INFO  EML file added
Thu May 16 19:07:11 2019: INFO  meta.xml archive descriptor written
Thu May 16 19:07:11 2019: INFO  Validating the core file: occurrence.txt. Depending on the number of records, this can take a while.
Thu May 16 19:07:11 2019: INFO  ? Validating the core basisOfRecord is always present and its value matches the Darwin Core Type Vocabulary.
Thu May 16 19:07:11 2019: INFO  ? Validating the core ID field occurrenceID is always present and unique.
Thu May 16 20:19:45 2019: INFO  ✓ Validated each line has a occurrenceID, and each occurrenceID is unique
Thu May 16 20:19:45 2019: INFO  ✓ Validated each line has a basisOfRecord, and each basisOfRecord matches the Darwin Core Type Vocabulary
Thu May 16 20:19:45 2019: INFO  Archive validated
Thu May 16 20:46:05 2019: INFO  Archive has been compressed
Thu May 16 20:46:05 2019: INFO  Archive version #92.144 generated successfully!
Thu May 16 20:46:15 2019: INFO  Adding or updating version: 92.144
Thu May 16 20:46:15 2019: INFO  Updating VersionHistory for version 92.144
```

Although the IPT has a temporary directory $datadir/tmp, the system default (usually /tmp) is used by `sort`, so that's a possible place for failure -- how does sort behave if there isn't enough space here?

Otherwise, we are indeed moving more data around than we need to. 

`ioping -c 10 -s 10M /nfslocation/` gives me 106MiB/s for ipt.gbif.org. (On fairly old hardware, on a new server it's 800MiB/s.)

**Comment by mskyttner** [comment] 2019-05-20 11:29
Thanks for looking into this. On our side we will proceed in two ways: a) ask the museum IT to investigate the slow io on the VMWare hypervisor VM that is our production environment and b) attempt an alternate approach in the meanwhile. 

For a) these inputs are welcome, since they give good reference points that we can add to the metrics we already have provided to the museum's IT department so they can look into the apparently slow disk io speed that we see when comparing our IPT production server to other environments. Could you also give the spec for the box doing the 3.5 hour validation?

I vaguely recall seeing various file segments generated in the $datadir/tmp but will take a look at what is going on in /tmp too. And we could perhaps also do the "select ... order by occurrenceID" too as suggested by Tim.

Just a couple of more clarifications, and I could launch a separate ticket for these if you prefer. If not here goes:

Can you clarify  whether "an IPT is needed for this"? 

Would the alternative workflow here be a command-line based publication of this dataset that would make use of the GBIF Registry API directly and bypassing the validation steps in IPT? Ie from https://www.gbif.org/developer/registry#datasets it looks like it would be a PUT to update the dataset and then a POST to get it crawled?

If so what steps would need to be taken to bump the version number? Ie these two lines in the log:

```bash
Thu May 16 20:46:15 2019: INFO  Adding or updating version: 92.144
Thu May 16 20:46:15 2019: INFO  Updating VersionHistory for version 92.144
```
Should we look at the source code in IPT to figure out how to do that or is there a write-up or docs for how to do bump the version nr in the right way using say bash, python or R?

**Comment by MattBlissett** [comment] 2019-05-20 12:13
The 3½ hour validation was done on a desktop system with a Xeon E5-1650 v3 @ 3.50GHz, 32GiB RAM, and the data on a local partition giving 370MiB/s with ioping.

If it's useful, I can repeat the process on ipt.gbif.org, which is probably more realistic as it is using NFS storage.

----

> Would the alternative workflow here be a command-line based publication of this dataset that would make use of the GBIF Registry API directly and therfore offering complete bypassing the validation steps in IPT?

Yes.

You need one POST to add an endpoint for a new location for the DWCA, and two DELETEs to remove the old ones. See https://github.com/gbif/registry/tree/master/registry-examples/src/test/scripts for example.

After that, you only need POST to request a crawl, as the metadata is updated based on the EML within the DWCA.  For a new version, the IPT changes some values in the EML: the packageId, pubDate and dc:replaces. I think the pubDate is the only one that we use.

I'm afraid there  isn't any extra documentation on this.

**Comment by mskyttner** [comment] 2019-05-22 11:28
Thank you @MattBlissett . Those docs should be sufficient, esp the bash-script is helpful. 

Some follow-up questions on the workflow for the Registry API usage:

- If I were to use two POSTs to create two endpoints for this dataset in the UAT - something the current Artportalen dataset has at gbif.org - with one for the DWC_ARCHIVE and another one for the EML - will the eml.xml inside the DWCA_ARCHIVE still be the only one used in the crawl or will the eml.xml on the EML-url endpoint override the EML data provided in the archive if they differ? I guess the EML data shouldn't differ if referential integrity is good, but it could still differ due to a mistake?

- The https://www.gbif-uat.org/health reports ingestion "not usable" currently, should I wait with testing it in the UAT?

**Comment by MattBlissett** [comment] 2019-05-23 13:47
① The EML within the archive is used. An EML endpoint is only used if it is the *only* endpoint (usually the case for METADATA type datasets).

② We have been using the UAT system for some testing as we make an important change to a backend database. We may need to do further testing, but we will work around anything we notice you're doing with the UAT system.

You can test on UAT. For permission to make changes through the API, you'll need to be granted permission. It's best if this is done using a special account, rather than your personal GBIF.org account.

Could you create an account on GBIF.org, and the same username on GBIF-UAT.org, for example with the username "gbif.se".  I will then grant it the necessary permissions.

**Comment by mskyttner** [comment] 2019-05-23 13:57
I will use a single endpoint then.

I have now created a separate account for this purpose on gbif.org and the uat using "bioatlas".

**Comment by MattBlissett** [comment] 2019-05-23 14:32
I don't see any new users on either system…

**Comment by mskyttner** [comment] 2019-05-23 15:09
Hmm... I didn't realize that the captcha was in several steps. I tried again in both now.

**Comment by shahmanash** [comment] 2019-05-29 21:14
After changing the query to do the sorting based on occurrenceID while fetching from the database itself, the publishing of the dataset has now resumed and seems to have completed in normal time.

**Comment by steinho** [comment] 2020-01-13 11:53
Slow validation of occurenceIds on docker image may be related to this?
https://github.com/gbif/docker-ipt/pull/8

**Comment by timrobertson100** [comment] 2021-04-28 09:46
@shahmanash 
Can you please confirm we can close this?

**Closed** 2021-05-26 14:52 UTC
Labels: Component-Docs
